branches:
  only:
    - master

sudo: required
services:
  - docker

env:
  global:
    - DATE=$(date '+%Y%m%d')
    - REPO="threathuntproj"
    - IMAGE_NAME="hunting"
    - JUPYTER_NB_PASS=""

before_script:
  - docker images

script:
  - docker build --pull --build-arg JUPYTER_NB_PASS=$JUPYTER_NB_PASS -t $REPO/$IMAGE_NAME:$DATE.$TRAVIS_BUILD_NUMBER .
  - docker images
  - docker run -v `pwd`:/home/jovyan/work $REPO/$IMAGE_NAME:$DATE.$TRAVIS_BUILD_NUMBER jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=60 --output /tmp/testoutput-py3.ipynb /home/jovyan/work/Test.ipynb
  - docker run -v `pwd`:/home/jovyan/work $REPO/$IMAGE_NAME:$DATE.$TRAVIS_BUILD_NUMBER jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=60 --output /tmp/testoutput-spark-py3.ipynb /home/jovyan/work/Test-spark.ipynb
  - docker images

before_deploy:
  - docker tag $REPO/$IMAGE_NAME:$DATE.$TRAVIS_BUILD_NUMBER $REPO/$IMAGE_NAME:latest
  - docker tag $REPO/$IMAGE_NAME $REPO/$IMAGE_NAME:$DATE
  - docker images
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh
